Add services page
crate/cloud-docs pull request #36
Opened 2023-10-03 05:50 UTC by proddata

## Summary of the changes / Why this is an improvement
Add page describing our service offerings.

## Checklist

 - [ ] Link to issue this PR refers to (if applicable): 
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

2023-10-03 11:43 UTC, amotl requested changes
I love the whole page, and added some suggestions at your disposal.

2023-10-03 11:43 UTC, amotl commented on docs/reference/services.md
> +have dedicated resources.
```suggestion
variability makes it less predictable compared to Dedicated Plans, where your
database is running on dedicated resources.
```

2023-10-03 11:43 UTC, amotl commented on docs/reference/services.md
> +The Shared Plan operates on a fair-use principle. All users are expected to use
```suggestion
The Shared Plan operates on a fair-use principle. All users are expected to utilize
```

2023-10-03 11:43 UTC, amotl commented on docs/reference/services.md
> +While it's possible to start with just one node, for applications requiring high
```suggestion
While it's possible to start with just one node, for applications needing high
```

2023-10-03 11:43 UTC, amotl commented on docs/reference/services.md
> +For organizations with specialized requirements that go beyond our Shared and
```suggestion
For organizations with specialized requirements that go beyond the Shared and
```

2023-10-03 11:43 UTC, amotl commented on docs/reference/services.md
> +Whether you have stringent compliance mandates, complex integrations, or unique
New paragraph, for a better stage of the "final words" on this page. ;]
```suggestion

Whether you have stringent compliance mandates, complex integrations, or unique
```

2023-10-03 11:43 UTC, amotl commented on docs/reference/services.md
> +expertise to meet your business objectives.
```suggestion
expertise to meet your business objectives and technical requirements.
```

2023-10-17 06:59 UTC, joncombe commented on docs/reference/services.md
> +7 more days of idleness. They cannot be scaled or changed.
I feel "inactivity" is a better word that "idleness". Not a big issue, just a suggestion.

2023-10-17 07:00 UTC, joncombe approved these changes
Approved with just one comment.

2023-10-17 07:05 UTC, merged