Add import globbing docs
crate/cloud-docs pull request #48
Opened 2023-12-05 00:12 UTC by matkuliak

## Summary of the changes / Why this is an improvement

Added brief globbing docs

## Checklist

 - [ ] Link to issue this PR refers to (if applicable): 
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

2023-12-09 19:13 UTC, amotl requested changes
Thanks for improving that section. I've added a few suggestions, feel free to use them or not.

2023-12-09 19:13 UTC, amotl commented on docs/reference/overview.rst
> +be charged for egress, depending on your provider. There is also a limit of 10
```suggestion
be charged for egress traffic, depending on your provider. There is also a volume limit of 10
```

2023-12-09 19:13 UTC, amotl commented on docs/reference/overview.rst
> +GiB for S3 imports. The usual file formats are supported.
Is it "per-file", actually?
```suggestion
GiB per file for S3 imports. The usual file formats are supported.
```

2023-12-09 19:13 UTC, amotl commented on docs/reference/overview.rst
> +GiB for S3 imports. The usual file formats are supported.
> The usual file formats are supported.

Which ones?

2023-12-09 19:13 UTC, amotl commented on docs/reference/overview.rst
> +~~~~~~~~~~~~~~~
Globbing is a pretty technical term. Maybe use "wildcard" instead?

2023-12-09 19:13 UTC, amotl commented on docs/reference/overview.rst
> +
What about such a little introductory paragraph before going into the technical details?

> You can import multiple files from an S3 bucket at once by using the well-known
> wildcard notation, also known as "globbing". In computer programming, [glob patterns]
> specify sets of filenames with [wildcard characters].

[glob patterns]: https://en.wikipedia.org/wiki/Glob_(programming
[wildcard characters]: https://en.wikipedia.org/wiki/Wildcard_characters

2023-12-20 15:23 UTC, proddata commented on docs/reference/overview.rst
> +Import globbing
```suggestion
Importing multiple files
```

2023-12-20 15:24 UTC, proddata commented
Can we adjust this PR to also reflect the changes of https://github.com/crate/cloud/issues/1505 (Azure Import).
This is similiar to S3 Imports and also supports multi file imports

2023-12-27 11:08 UTC, matkuliak commented
Added section on imports for Azure Container/Blob Storage and also mentioned it in multiple-files-import section.

2023-12-27 14:36 UTC, proddata commented on docs/reference/overview.rst
> +^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
Import from Azure Blob Storage Container
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-12-27 15:07 UTC, SStorm commented on docs/reference/overview.rst
> +supported - CSV, Json, and Parquet.
```suggestion
supported - CSV (all variants), Json (JSON-Lines, JSON Arrays and JSON Documents), and Parquet.
```

2023-12-27 15:48 UTC, proddata commented on docs/reference/overview.rst
> +level.
this seems to be a duplicate. maybe something like this ?

```suggestion
Importing data from private Azure Blob Storage containers is possible using a stored secret, which includes a secret name and either an Azure Storage Connection string or an Azure SAS Token URL. An admin user at the organization level can add this secret.
```

2024-01-08 14:10 UTC, proddata approved these changes

2024-01-08 14:37 UTC, amotl approved these changes
Thank you 👍. Maybe squash the commits before merging?

2024-01-08 14:44 UTC, merged