Home & Features: Features: Add canonical feature page for "CrateDB Cloud"
crate/cloud-docs pull request #88
Opened 2024-11-16 02:18 UTC by amotl

## What's Inside
- Features: Add canonical feature page for "CrateDB Cloud"
- Features: Add "Learn" rubric
- Home: Update layout of entry point page

## Preview
_Rendering._

## What's Inside
A compressed variant of https://cratedb.com/product/cloud.

2024-11-19 21:02 UTC, proddata requested changes
I am still unclear about the purpose of the “All Features” pages. They appear to add unnecessary complexity with limited benefits, potentially creating a hurdle in the user experience.

Additionally, this specific patch seems to include outdated screenshots, which might have been taken from other parts of the documentation that also require updating.

2024-11-29 12:25 UTC, widmogrod reviewed
I read through the changes. Grammatically and visually, they look good.

Refreshed CrateDB Cloud page looks nicer. Indeed, a newer screenshot could be used. But as I understand it, this is not a new asset, so maybe in a separate PR, we could refresh/modernize all images.

As for the All features page, what I found confusing is the duplication of sub-sections: 
<img width="269" alt="image" src="https://github.com/user-attachments/assets/8cb376ce-6287-45c1-bf08-b197a6c79985">
Is there a way to change it, and have all features more like a landing page that just list them? or maybe it would make more sense to merge All Features with CrateDB Cloud page (I think I like the last option)? @proddata any oppionon about it?

2024-11-29 14:26 UTC, amotl commented
## Problem
> As for the All features page, what I found confusing is the duplication of sub-sections:
> Is there a way to change it, and have all features more like a landing page that just list them?

## Solution
- **Patch:** https://github.com/crate/crate-docs-theme/pull/556
- **Preview:** https://crate-cloud--88.org.readthedocs.build/en/88/feature/

## How it is done...
... is certainly quirky, but c'est la vie. It should not block this patch in general now that there is a solution for this obstacle. In the future, those explorations might yield a "programmable" navigation component, that will have a better usability than fiddling with conditionals in Sphinx/Jinja templating. But well, this is not concern right now.

- https://github.com/tech-writing/sphinx-design-elements/pull/11
- https://github.com/crate/crate-docs-theme/pull/405

2024-11-30 11:37 UTC, proddata commented
I don’t see much value in this refactor. To me, it still seems to complicate the user journey rather than improve it. If we want to highlight specific features, this should be done on the cloud homepage, not on a separate page. Additionally, we should avoid cluttering the design with numerous logos or images that simply repeat the text.

Thank you for giving it a try; however, I will close this for now until we have a clearer understanding of what we want to achieve and how this change helps users navigate the documentation or better understand the product.

2025-08-14 14:12 UTC, amotl commented
Hi Brian,

> Main point being this seems more of an index to whole cloud section.

Yes, that's its purpose.

> So it should not have it's own page but be part of the "CrateDB Cloud" page, and not have the pages in the left navbar - they are very confusing as they are not pages.

Right, please don't get distracted by those details which are artefacts because things are still in flux but focus on the main idea instead to improve content bundling and presentation, for a better guidance than before, in this case in a "everything important on one page" spirit. This new page effectively just indexes into existing content in order to present it in a different way to encourage discussions -- again, please don't get lost in certain details when evaluating.

> I would suggest to not focus on this for now and revisit later in case I'm missing the whole point.

Sure, I think we will touch this topic once more when we start getting our hands dirty by working on the topic together more closely.

With kind regards,
Andreas.

2025-08-14 14:55 UTC, amotl commented
Hi again. Thanks for your feedback again.

>> So it should not have it's own page but be part of the "CrateDB Cloud" page, and not have the pages in the left navbar - they are very confusing as they are not pages.
>
> Right, please don't get distracted by those details [...]

Based on your admonition about wrong slotting, I've relocated the content now to the main `index` page. As such, the navigation artefacts you have been mentioning are gone. Please have a look with a fresh eye.

2025-08-14 14:56 UTC, amotl commented on docs/requirements.txt
> +crate-docs-theme>=0.37.2.dev0
This is probably no longer required.

2025-08-14 14:57 UTC, amotl commented on docs/requirements.txt
> +crate-docs-theme>=0.37.2.dev0
Fixed with 12ec35d8f3cb6.

2025-08-14 15:10 UTC, amotl commented on docs/index.md
>  :::
@coderabbitai: However in reality it works, thanks.

2025-09-15 21:38 UTC, amotl commented
Thanks for your feedback. We think all admonitions have been addressed now. Please have a look with a fresh eye.

-- https://crate-cloud--88.org.readthedocs.build/en/88/

2025-09-17 06:52 UTC, merged